bacon_ingredient = Ingredient.create(name: "bacon", calories: 250, amount: 0.5)
tomato_ingredient = Ingredient.create(name: "tomato", calories: 60, amount: 0.3)
lettuce_ingredient = Ingredient.create(name: "lettuce", calories: 30, amount: 0.3)
bacon_sandwich = Sandwich.create(name: "Bacon sandwich", bread_type: "regular")
bacon_sandwich.ingredients.push(bacon_ingredient)
