# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f033c8bb8e03758211a32de21f07d75865c12f986b630ee508060befa96628d21ecc2f910020a97d2a6bf37ad732fc878a2b2a41ad226831483668ef5e5f8a9

test:
  secret_key_base: 199fc89d0891448f07e37be545be8f3ea7c45888757674e04e3f6da2cc9eb8b24c825e4d826c05aecdb4c80bad8b4807013e86a5ceb540c1d39eaf6ece284649

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
